### DISCUSSION TITLE
Spring Properties에 대해서 설명해주세요.

### DISCUSSION THREAD

**Discussion by le2sky** [2024-woowacourse-study/level-interview#217] [Spring Core]
뭘까용

**Comment by jimi567** [comment]
Spring Properties는 Spring 프레임워크에서 애플리케이션 설정값을 관리하고 외부화하기 위해 사용되는  개념입니다. Spring Properties를 통해 애플리케이션 설정을 코드에서 분리하여 환경에 따라 쉽게 변경할 수 있습니다. 주로 application.properties 또는 application.yml 파일을 사용하여 설정값을 정의합니다.

많은 크루들이 yml이 가독성이 좋다고 얘기를 해서, yml 기준으로 예시를 들면,

```yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: pass
```
이러한 형태로 관련 설정값을 정의할 수 있습니다.

Spring boot에서는 기본적으로 src/main/resources/ 경로에서 yml. 또는 properties 파일을 찾아 설정값을 찾게 됩니다.

실제 설정값을 읽을 때는, @Value, @ConfigurationProperties 등을 사용해 값을 바인딩 하게 됩니다. 
[@Value](https://github.com/2024-woowacourse-study/level-interview/discussions/227)
[@ConfigurationPropetries](https://github.com/2024-woowacourse-study/level-interview/discussions/169)
  
추가적으로, 프로파일 등을 설정하여, 환경별로(배포, 개발, 로컬 등) 설정값을 다르게 사용할 수 있습니다. 
예를 들면,  
+ application-dev.properties 또는 application-dev.yml
+ application-prod.properties 또는 application-prod.yml  

형태로 설정값을 환경에 따라 구분하여 관리할 수 있습니다.
+ [@Profile](https://github.com/2024-woowacourse-study/level-interview/discussions/219)
